return {
    ['unused-local']        = 'Hint',
    ['unused-function']     = 'Hint',
    ['undefined-global']    = 'Warning',
    ['global-in-nil-env']   = 'Warning',
    ['unused-label']        = 'Hint',
    ['unused-vararg']       = 'Hint',
    ['trailing-space']      = 'Hint',
    ['redefined-local']     = 'Hint',
    ['newline-call']        = 'Information',
    ['newfield-call']       = 'Warning',
    ['redundant-parameter'] = 'Hint',
    ['ambiguity-1']         = 'Warning',
    ['lowercase-global']    = 'Information',
    ['undefined-env-child'] = 'Information',
    ['duplicate-index']     = 'Warning',
    ['empty-block']         = 'Hint',
    ['redundant-value']     = 'Hint',
    ['set-const']           = 'Error',

    ['duplicate-doc-class'] = 'Warning',
}
