local vm = require 'vm.vm'
require 'vm.getGlobals'
require 'vm.getLinks'
require 'vm.getGlobal'
require 'vm.getLibrary'
require 'vm.getValue'
require 'vm.getClass'
require 'vm.getMeta'
require 'vm.eachField'
require 'vm.eachDef'
require 'vm.eachRef'
return vm
