local vm = require 'vm.vm'
require 'vm.getGlobals'
require 'vm.getDocs'
require 'vm.getLibrary'
require 'vm.getInfer'
require 'vm.getClass'
require 'vm.getMeta'
require 'vm.eachField'
require 'vm.eachDef'
require 'vm.eachRef'
require 'vm.getLinks'
require 'vm.guideInterface'
return vm
