local guide = require 'parser.guide'


assert(guide.isLegalName 'abc')
assert(guide.isLegalName '_abc')
assert(guide.isLegalName 'a123')
assert(guide.isLegalName '_')
assert(not guide.isLegalName '1abc')
assert(not guide.isLegalName 'a b')
assert(not guide.isLegalName '')
assert(not guide.isLegalName 'a.b')

assert(not guide.isLegalName 'and')
assert(not guide.isLegalName('and', 'Lua 5.1'))
assert(not guide.isLegalName('and', 'LuaJIT'))
assert(not guide.isLegalName 'end')
assert(not guide.isLegalName 'true')
assert(not guide.isLegalName 'false')
assert(not guide.isLegalName 'nil')

assert(guide.isKeyWord 'and')
assert(guide.isKeyWord 'while')
assert(not guide.isKeyWord 'true')
assert(not guide.isKeyWord 'abc')
assert(guide.isReservedWord 'true')
assert(guide.isReservedWord 'nil')
assert(not guide.isReservedWord 'and')
assert(not guide.isReservedWord 'abc')

assert(not guide.isLegalName 'goto')
assert(not guide.isLegalName('goto', 'Lua 5.2'))
assert(not guide.isLegalName('goto', 'Lua 5.3'))
assert(not guide.isLegalName('goto', 'Lua 5.4'))
assert(not guide.isLegalName('goto', 'Lua 5.5'))
assert(guide.isLegalName('goto', 'Lua 5.1'))
assert(guide.isLegalName('goto', 'LuaJIT'))
assert(guide.isLegalName('goto', 'LuaJIT'))

assert(guide.isKeyWord('goto', 'Lua 5.2'))
assert(guide.isKeyWord('goto', 'Lua 5.5'))
assert(not guide.isKeyWord('goto', 'Lua 5.1'))
assert(not guide.isKeyWord('goto', 'LuaJIT'))

assert(guide.isLegalName 'global')
assert(guide.isLegalName('global', 'Lua 5.5'))
assert(guide.isLegalName('global', 'Lua 5.4'))
assert(guide.isLegalName('global', 'Lua 5.1'))
assert(guide.isLegalName('global', 'LuaJIT'))
assert(not guide.isKeyWord('global', 'Lua 5.5'))
assert(guide.isLegalName('global', 'Lua 5.4'))
assert(guide.isLegalName('continue', 'Lua 5.4'))

assert(not guide.isLegalName('goto', 'NotALua'))

assert(not guide.isLegalName('中文字段'))
assert(guide.isLegalName('中文字段', nil, true))
assert(not guide.isLegalName('1中文', nil, true))
assert(guide.isLegalName('中_文2', nil, true))

assert(guide.isWordChar '_')
assert(guide.isWordChar 'a')
assert(guide.isWordChar 'Z')
assert(guide.isWordChar '9')
assert(guide.isWordChar '中')
assert(not guide.isWordChar '.')
assert(not guide.isWordChar ' ')
assert(not guide.isWordChar '')

assert(ls.guide == guide)