name: Documentation Report
description: Report an issue with documentation in the lua-language-server.
labels:
  - documentation
assignees:
  - carsakiller
body:
  - type: markdown
    attributes:
      value: >
        For issues with our [website](https://luals.github.io) and its wiki,
        please visit the [correct repository](https://github.com/LuaLS/LuaLS.github.io/issues).
  - type: markdown
    attributes:
      value: >
        **Please check for similar issues before continuing!**
  - type: textarea
    id: expected
    attributes:
      label: Issue Description
      description: Please describe the documentation issue. Is something incorrect, missing or improveable?
    validations:
      required: true
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: >
        Please provide any additional notes, context,
        and media you have.
  - type: markdown
    attributes:
      value: |
        Thank you very much for helping improve the language server! ❤️
