return {
    ['unused-local']        = 'Hint',
    ['undefined-global']    = 'Warning',
    ['unused-label']        = 'Hint',
    ['unused-vararg']       = 'Hint',
    ['trailing-space']      = 'Hint',
    ['redefined-local']     = 'Hint',
    ['newline-call']        = 'Information',
    ['redundant-parameter'] = 'Hint',
    ['ambiguity-1']         = 'Warning',
    ['lowercase-global']    = 'Information',
    ['undefined-env-child'] = 'Information',
    ['duplicate-index']     = 'Warning',
    ['duplicate-method']    = 'Warning',
    ['empty-block']         = 'Hint',
    ['redundant-value']     = 'Hint',
    ['emmy-lua']            = 'Warning',
    ['set-const']           = 'Error',
}
