test.require 'test.project.index'
test.require 'test.project.require'
test.require 'test.project.require-path'
test.require 'test.project.require-cache'
test.require 'test.project.global-cache'
test.require 'test.project.global-cache2'
test.require 'test.project.self'
test.require 'test.project.external'
