---@class LuaLS.Node
ls.node = {}

require 'node.cache_module'
require 'node.node'
require 'node.class'
require 'node.alias'
require 'node.type'
require 'node.value'
require 'node.union'
require 'node.table'
require 'node.vararg'
require 'node.tuple'
require 'node.array'
require 'node.index'
require 'node.function'
require 'node.intersection'
require 'node.unsolve'
require 'node.generic'
require 'node.generic_context'
require 'node.call'
require 'node.variable'
require 'node.template'

require 'node.manager'
