-- [已迁移至 test/feature/completion/word.lua] local zabcde / za<??>

-- [SKIPPED][continue-typing] 旧 TEST 宏会模拟连续输入上下文；TEST_COMPLETION 当前不支持该模式。
-- TEST_COMPLETION [[
-- -- zabcde
-- io.z<??>
-- ]] {
-- 	{
-- 		label = 'zabcde',
-- 		kind = ls.spec.CompletionItemKind.Text,
-- 	}
-- }

-- [SKIPPED][continue-typing] 旧 TEST 宏会模拟连续输入上下文；TEST_COMPLETION 当前不支持该模式。
-- TEST_COMPLETION [[
-- -- provider
-- pro<??>
-- ]] {
-- 	{
-- 		label = 'provider',
-- 		kind = ls.spec.CompletionItemKind.Text,
-- 	}
-- }

-- [SKIPPED][continue-typing] 单引号内继续输入枚举补全依赖旧 continue-typing 测试上下文。
-- TEST_COMPLETION [[
-- ---@param n '"abcdefg"'
-- local function f(n) end
--
-- f 'abc<??>'
-- ]] {
-- 	{
-- 		label    = "'abcdefg'",
-- 		kind     = ls.spec.CompletionItemKind.EnumMember,
-- 		textEdit = EXISTS,
-- 	}
-- }

-- [SKIPPED][continue-typing] 比较表达式中的单引号继续输入补全依赖旧 continue-typing 测试上下文。
-- TEST_COMPLETION [[
-- ---@type '"abcdefg"'
-- local t
--
-- if t == 'abc<??>'
-- ]] {
-- 	{
-- 		label    = "'abcdefg'",
-- 		kind     = ls.spec.CompletionItemKind.EnumMember,
-- 		textEdit = EXISTS,
-- 	}
-- }
