FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update

# Install C++ compiler
RUN apt-get install build-essential

# Install Ninja build tool
RUN apt-get install ninja-build

EXPOSE 5050
