---@class any
---@class string   any
---@class number   any
---@class integer  number
---@class boolean  any
---@class table    any
---@class function any
---@class nil      any
---@class userdata any
---@class thread   any

---@alias GCOption string
---| > '"collect"'      # 做一次完整的垃圾收集循环。
---|   '"stop"'         # 停止垃圾收集器的运行。
---|   '"restart"'      # 重启垃圾收集器的自动运行。
---|   '"count"'        # 以 K 字节数为单位返回 Lua 使用的总内存数。
---|   '"step"'         # 单步运行垃圾收集器。
---|   '"setpause"'     # 设置收集器的 `间歇率`。
---|   '"setstepmul"'   # 设置收集器的 `步进倍率`。
---|   '"incremental"'  # 改变收集器模式为增量模式。
---|   '"generational"' # 改变收集器模式为分代模式。
---|   '"isrunning"'    # 返回表示收集器是否在工作的布尔值。

---@alias loadOption string
---|   "'b'"            # 只能是二进制代码块。
---|   "'t'"            # 只能是文本代码块。
---| > "'bt'"           # 可以是二进制也可以是文本。
