require 'tclient.tests.single-mode'
require 'tclient.tests.library-ignore-limit'
require 'tclient.tests.multi-workspace'
require 'tclient.tests.folders-with-single-file'
require 'tclient.tests.load-library'
require 'tclient.tests.files-associations'
require 'tclient.tests.resolve-completion'
require 'tclient.tests.performance-1'
