require 'tclient.tests.single-mode'
require 'tclient.tests.library-ignore-limit'
require 'tclient.tests.multi-workspace'
require 'tclient.tests.folders-with-single-file'
require 'tclient.tests.load-library'
require 'tclient.tests.files-associations'
require 'tclient.tests.resolve-completion'
require 'tclient.tests.hover-pairs'
require 'tclient.tests.change-workspace-folder'
require 'tclient.tests.jump-source'
require 'tclient.tests.load-relative-library'
require 'tclient.tests.hover-set-local'
require 'tclient.tests.same-prefix'
require 'tclient.tests.recursive-runner'
require 'tclient.tests.modify-luarc'

require 'tclient.tests.performance-jass-common'
require 'tclient.tests.build-meta'
