local searcher = require 'searcher.searcher'
require 'searcher.eachField'
require 'searcher.eachRef'
require 'searcher.eachDef'
require 'searcher.getGlobals'
require 'searcher.getLinks'
require 'searcher.getGlobal'
require 'searcher.getLibrary'
require 'searcher.getValue'
return searcher
