test.require 'test.tools.afs'
test.require 'test.tools.textmerger'
test.require 'test.tools.time'
test.require 'test.tools.memory-guard'
test.require 'test.tools.facts'
-- test.require 'test.tools.filewatch'
